### ISSUE TITLE
Research Python Google Sheets API

### ISSUE THREAD

**Issue by josueal1** [SHPE-at-UCI/shpesignin#20]
Find a way to use Python to send data

**Comment by Guvn0** [comment]
update:
Got it working on well on python and iffy on javascript, however currently all operations are done on google sheets, python only reads in and writes data. Two main operations addNew (adds data to next available line) and find (gets the position of data or -1 if doesn't exist)

**Comment by Guvn0** [comment]
improved version under branch google-sheetsV2, original may not work correctly as I may have killed the project that the credentials file used there

**Comment by josueal1** [comment]
Functionality tested by @guilleeh
